export const ROUTES = {
  DASHBOARD: '/',
  AR: '/ar',
  AR_INVOICES: '/ar/invoices',
  AR_COLLECTIONS: '/ar/collections',
  AR_RECONCILIATION: '/ar/reconciliation',
  AR_RETAINAGE: '/ar/retainage',
  AR_AGING: '/ar/aging',
  AP: '/ap',
  AP_INVOICES: '/ap/invoices',
  AP_POS: '/ap/purchase-orders',
  AP_PAYMENTS: '/ap/payments',
  AP_SUBCONTRACTORS: '/ap/subcontractors',
  AP_AGING: '/ap/aging',
  SETTINGS: '/settings',
  SETTINGS_ADE: '/settings/ade',
  SETTINGS_WORKFLOWS: '/settings/workflows',
  SETTINGS_USERS: '/settings/users',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_INTEGRATIONS: '/settings/integrations',
  AUDIT_LOG: '/audit-log',
};

export const STATUS_COLORS: Record<string, { bg: string; text: string; dot: string }> = {
  Current:     { bg: 'bg-green-50',  text: 'text-green-700',  dot: 'bg-green-500' },
  Paid:        { bg: 'bg-green-50',  text: 'text-green-700',  dot: 'bg-green-500' },
  Partial:     { bg: 'bg-blue-50',   text: 'text-blue-700',   dot: 'bg-blue-500' },
  Overdue:     { bg: 'bg-red-50',    text: 'text-red-700',    dot: 'bg-red-500' },
  Disputed:    { bg: 'bg-orange-50', text: 'text-orange-700', dot: 'bg-orange-500' },
  Exception:   { bg: 'bg-yellow-50', text: 'text-yellow-700', dot: 'bg-yellow-500' },
  Processing:  { bg: 'bg-blue-50',   text: 'text-blue-700',   dot: 'bg-blue-500' },
  'Auto-Approved': { bg: 'bg-green-50', text: 'text-green-700', dot: 'bg-green-500' },
  Approved:    { bg: 'bg-green-50',  text: 'text-green-700',  dot: 'bg-green-500' },
  Scheduled:   { bg: 'bg-purple-50', text: 'text-purple-700', dot: 'bg-purple-500' },
  Queued:      { bg: 'bg-indigo-50', text: 'text-indigo-700', dot: 'bg-indigo-500' },
  'Non-Compliant': { bg: 'bg-red-50', text: 'text-red-700',   dot: 'bg-red-500' },
  Compliant:   { bg: 'bg-green-50',  text: 'text-green-700',  dot: 'bg-green-500' },
  Pending:     { bg: 'bg-gray-100',  text: 'text-gray-600',   dot: 'bg-gray-400' },
  Draft:       { bg: 'bg-gray-100',  text: 'text-gray-600',   dot: 'bg-gray-400' },
  Held:        { bg: 'bg-red-50',    text: 'text-red-700',    dot: 'bg-red-500' },
  Active:      { bg: 'bg-blue-50',   text: 'text-blue-700',   dot: 'bg-blue-500' },
  Running:     { bg: 'bg-green-50',  text: 'text-green-700',  dot: 'bg-green-500' },
  Paused:      { bg: 'bg-yellow-50', text: 'text-yellow-700', dot: 'bg-yellow-500' },
};

export const COMPANY = {
  name: 'TCL Electrical & Lighting',
  shortName: 'TCL Electric',
  phone: '630.844.3274',
  email: 'info@tclelectric.com',
  address: 'Geneva, IL',
  controllerName: 'Tom Callahan',
  controllerTitle: 'Controller',
};
